version: "3.9"

services:
  app:
    restart: always
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - VIRTUAL_HOST=yourdomain.com
      - LETSENCRYPT_HOST=yourdomain.com
      - LETSENCRYPT_EMAIL=youremail@domain.com
    volumes:
      - ./apache/vhost.conf:/etc/apache2/sites-available/000-default.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.laravel.rule=Host(`yourdomain.com`)"
      - "traefik.http.routers.laravel.entrypoints=websecure"
      - "traefik.http.routers.laravel.tls.certresolver=lets-encrypt"

  traefik:
    image: traefik:v2.16
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.lets-encrypt.acme.email=youremail@domain.com"
      - "--certificatesresolvers.lets-encrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.lets-encrypt.acme.tlschallenge=true"
    ports:
      - "80:80"
      - "443:443"
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/letsencrypt:/letsencrypt
    networks:
      - laravel
